SubReddit v2/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Of_Comments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Comments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubReddit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SubReddit</label>
        <referenceTo>SubReddit__c</referenceTo>
        <relationshipLabel>Posts</relationshipLabel>
        <relationshipName>Posts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v1/objects/SubReddit__c.object
<CustomObject>
    <fields>
        <fullName>No_Of_Downvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Downvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_Of_Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No Of Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SubReddit</label>
    <nameField>
        <label>SubReddit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubReddit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/classes/fetchPostRecords.cls
public with sharing class fetchPostRecords {
    @AuraEnabled
    public static list<Post__c> getPostRecords(Id redditIds){
        list<Post__c> postRecords = new list<Post__c>();
        for(Post__c PObj : [Select id,Name,Body__c,No_Of_Downvotes__c,No_Of_Upvotes__c, SubReddit__c From Post__c where SubReddit__c =: redditIds ORDER BY No_Of_Upvotes__c desc NULLS LAST limit 10]){
            postRecords.add(PObj);
        }
         if(postRecords.size() == 0){
            throw new AuraHandledException('No Record Found..');
         }
        return postRecords;
    }
    @AuraEnabled
    public static list<Post__c> getPostList(string searchKey,Id redditIds) {
        string searchKeyword = '%' + searchKey + '%';
		
       // create contact list to store search result 
        list<Post__c> SubPostListRecord = new list<Post__c>();
     
	   // query contact records
        for(Post__c SRObj : [Select id,Name,No_Of_Downvotes__c,No_Of_Upvotes__c,Body__c, SubReddit__c,No_Of_Comments__c From Post__c
                            WHERE name LIKE : searchKeyword AND SubReddit__c =: redditIds]){
                        SubPostListRecord.add(SRObj);
        }
         if(SubPostListRecord.size() == 0){
            throw new AuraHandledException('No Record Found..'); 
         }
         
        return SubPostListRecord;
    }
}