SubReddit v1/objects/Comment__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comment</label>
        <referenceTo>Comment__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DownVotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label># DownVotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Post__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post</label>
        <referenceTo>Post__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Upvotes__c</fullName>
        <defaultValue>0</defaultValue>
        <label># Upvotes</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Comment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SubReddit v2/classes/childComments.cls
public with sharing class childComments {
    @AuraEnabled
    public static list<Comment__c> getChildCommentRecords(id parentCommentId, id commentPostId){

        list<Comment__c> childCommentsList = new list<Comment__c>();

        for(Comment__c SRObj : [Select id
        , Name
        , Comment__c
        , Post__c
        , Upvotes__c
        , DownVotes__c,Body__c
        , CreatedBy.name
        , CreatedBy.FirstName
        , CreatedBy.CreatedDate
        From Comment__c where Comment__c =: parentCommentId AND Post__c =:commentPostId]){
            childCommentsList.add(SRObj);
        }
         if(childCommentsList.size() == 0){
            throw new AuraHandledException('No Record Found..');
         }
         system.debug('childCommentsList :'+childCommentsList);

        return childCommentsList;
    }
}